---

- name: create dir
  file:
    path: /home/ubuntu/backend
    state: directory
    
- name: copy files
  copy:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/backend/artifact.tar.gz

- name: decompress
  shell: |
    cd /home/ubuntu/backend
    tar xvzf artifact.tar.gz -C .
      
- name: install, build
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm install
    npm run build
      
- name: start pm2
    become: true
    shell: |
      cd /home/ubuntu/backend
      pm2 start npm --name "backend" -- start
      echo "started pm2"
      pm2 ls
